### ISSUE TITLE
Ignore git action when *.md file changed

### ISSUE THREAD

**Issue by kaplanelad** [kaplanelad/shellfirm#29]
### Proposal
Reduce actions

### Attempted Solutions
```
on:
  push:

    paths-ignore:
      - '**/*.md'
```
